swagger: "2.0"
info:
  description: Swagger for File Operations
  version: "1.0.0"
  title: File Operations 
consumes:
  - application/json

basePath: /

paths:
  /v1/ping:
    get:
      tags:
      - "Health Check"
      summary: "ping pong application"
      description: "ping pong check"
      operationId: routes.ping
      responses:
        500:
          description: Server error
        200:
          description: Ping Successful
          schema:
            type: string


  /v1/fetch_data:
    get:
      tags:
      - "Document Operations"
      summary: "fetch details"
      description: "Fetch data from csv"
      operationId: routes.fetch_details
      produces:
      - "application/json"
      parameters:
      - name: "rows"
        in: "query"
        description: "Number of rows to fetch"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: json response

  /v1/search_file:
    post:
      tags:
      - "Document Operations"
      summary: "find details"
      description: ""
      operationId: "routes.search"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "order placed for purchasing the pet"
        required: true
        schema:
          type: "object"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid Order"